import { SourcingQuote } from '../types';

export const PRESET_QUOTES: { id: string; name: string; description: string; quote: SourcingQuote }[] = [
  {
    id: 'user_scenario_50k_units',
    name: '50,000 Units (0.30 RMB Factory → 0.35 RMB Quote)',
    description: 'Exact scenario: 50,000 units, Factory cost 0.30 RMB, Add 0.05 RMB profit -> Quote client 0.35 RMB. Sections kept completely independent.',
    quote: {
      id: 'quote_user_1',
      quoteNumber: 'CN-2026-50K',
      title: 'Bulk Sourcing Order (50,000 units)',
      clientName: 'Global Wholesale Buyer',
      clientCompany: 'Direct Import LLC',
      clientEmail: 'buyer@importllc.com',
      clientCountry: 'United States',
      dateCreated: new Date().toISOString().split('T')[0],
      validUntil: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
      incoterm: 'FOB Ningbo / DDP Optional',
      mode: 'full_quote',
      targetCurrency: 'CNY',
      items: [
        {
          id: 'item_user_50k',
          name: 'Custom Plastic / Silicone Product Component',
          sku: 'SKU-50K-01',
          quantity: 50000,
          factoryCostCurrency: 'CNY',
          factoryCostPerUnit: 0.30, // 0.30 RMB factory cost
          profitType: 'fixed',
          profitPerUnit: 0.05, // +0.05 RMB profit per unit -> gives 0.35 RMB quote to client!
          unitWeightKg: 0.02, // 20g
          packagingCostPerUnit: 0.00,
          packagingCurrency: 'CNY',
          notes: 'Factory wholesale price 0.30 RMB + 0.05 RMB agent profit = 0.35 RMB client quote',
          anchorCurrency: 'CNY',
          currencySnapshots: {
            CNY: { factoryCost: 0.30, profit: 0.05, packagingCost: 0 },
          },
        },
      ],
      shipping: {
        enabled: false, // Start with false or standalone so user can calculate product alone!
        method: 'sea_ddp',
        departurePort: 'Ningbo / Shenzhen',
        destinationCountry: 'United States',
        calcBasis: 'per_kg',
        grossWeightKg: 1000,
        costCurrency: 'USD',
        baseCostRate: 1.50,
        agentProfitType: 'per_kg',
        agentProfitValue: 0.30,
        transitTimeDays: '25-30 days',
        doorDeliveryIncluded: true,
      },
      customs: {
        enabled: false,
        tariffPercent: 3.5,
        customsClearanceFee: 120,
        customsFeeCurrency: 'USD',
        portHandlingFee: 80,
        portFeeCurrency: 'USD',
        agentMarkupType: 'fixed',
        agentMarkupValue: 50,
      },
      services: [],
      sourcingFeeType: 'none',
      sourcingFeeValue: 0,
      sourcingFeeCurrency: 'USD',
      paymentTerms: '30% deposit, 70% before container dispatch',
      agentCompanyName: 'China Sourcing & Logistics Partner',
      agentContact: 'agent@chinasourcing.com',
      notes: 'Product quoted strictly at 0.35 RMB per unit (50,000 units = 17,500 RMB). Shipping and customs quoted separately upon request.',
    },
  },
  {
    id: 'micro_margin_promo',
    name: 'Micro-Margin Bulk Sourcing (0.34 RMB / $0.05/unit)',
    description: 'High volume order (20,000 pcs) with tiny 0.34 RMB per-unit product margin, Sea DDP freight markup & customs',
    quote: {
      id: 'quote_micro_1',
      quoteNumber: 'CN-2026-081',
      title: 'Bulk Custom Promo Phone Stands (20,000 pcs)',
      clientName: 'Markus Henderson',
      clientCompany: 'Apex Brand Retail LLC',
      clientEmail: 'markus@apexbrand.com',
      clientCountry: 'United States',
      dateCreated: new Date().toISOString().split('T')[0],
      validUntil: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
      incoterm: 'DDP (Delivered Duty Paid - Door Delivery)',
      mode: 'full_quote',
      targetCurrency: 'USD',
      items: [
        {
          id: 'item_1',
          name: 'Foldable Aluminum Phone Stand (Custom Laser Logo)',
          sku: 'STND-AL-01',
          quantity: 20000,
          factoryCostCurrency: 'CNY',
          factoryCostPerUnit: 3.85, // 3.85 RMB factory price
          profitType: 'fixed',
          profitPerUnit: 0.34, // Exactly 0.34 RMB micro margin!
          unitWeightKg: 0.085, // 85g
          cbmPerUnit: 0.00015,
          packagingCostPerUnit: 0.30, // 0.30 RMB retail kraft box
          packagingCurrency: 'CNY',
          notes: 'Anodized black finish, individual retail box with UPC barcode',
        },
      ],
      shipping: {
        enabled: true,
        method: 'sea_ddp',
        departurePort: 'Ningbo Port',
        destinationCountry: 'United States (Los Angeles Warehouse)',
        destinationCity: 'Ontario, CA',
        calcBasis: 'per_kg',
        grossWeightKg: 1700, // 20000 * 0.085 kg
        volumetricWeightKg: 1850,
        cbm: 3.2,
        costCurrency: 'USD',
        baseCostRate: 1.45, // $1.45/kg base sea freight DDP
        agentProfitType: 'per_kg',
        agentProfitValue: 0.25, // Agent adds +$0.25/kg markup on freight
        transitTimeDays: '22-26 days',
        doorDeliveryIncluded: true,
        notes: 'Matson Fast Boat to Long Beach + UPS Ground to final warehouse',
      },
      customs: {
        enabled: true,
        tariffPercent: 3.5, // 3.5% tariff
        customsClearanceFee: 120, // $120 clearance
        customsFeeCurrency: 'USD',
        portHandlingFee: 80,
        portFeeCurrency: 'USD',
        agentMarkupType: 'fixed',
        agentMarkupValue: 50, // +$50 agent customs handling profit
        notes: 'Section 301 and standard entry paperwork included',
      },
      services: [
        {
          id: 'srv_1',
          name: 'Pre-Shipment Quality Inspection (PSI)',
          costCurrency: 'USD',
          agentBaseCost: 150, // Agent pays local inspector
          clientPriceCurrency: 'USD',
          clientPrice: 220, // Client charged $220
          unitType: 'fixed',
          description: 'AQL Level II Major 2.5 / Minor 4.0 standard 250 units sample pull',
        },
      ],
      sourcingFeeType: 'none',
      sourcingFeeValue: 0,
      sourcingFeeCurrency: 'USD',
      paymentTerms: '30% deposit to commence production, 70% before loading container',
      leadTimeWeeks: '20-25 days',
      agentCompanyName: 'Pacific Bridge Sourcing Ltd.',
      agentContact: 'sourcing@pacificbridge.cn | WeChat: sourcing_pro',
      notes: 'Prices include all tooling, custom logo printing, packaging, customs, and door-to-door freight.',
    },
  },
  {
    id: 'air_ddp_electronics',
    name: 'Air Cargo DDP Electronics (Multi-Item Order)',
    description: 'Medium batch consumer accessories with tiny per-unit sourcing gain ($0.05) + Air DDP shipping markup',
    quote: {
      id: 'quote_air_2',
      quoteNumber: 'CN-2026-094',
      title: 'TWS Earbuds & Fast Chargers (3,000 pcs total)',
      clientName: 'Oliver Smith',
      clientCompany: 'Nordic Gear Imports',
      clientEmail: 'oliver@nordicgear.co.uk',
      clientCountry: 'United Kingdom',
      dateCreated: new Date().toISOString().split('T')[0],
      validUntil: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
      incoterm: 'DDP (Delivered Duty Paid to London)',
      mode: 'full_quote',
      targetCurrency: 'GBP',
      items: [
        {
          id: 'item_tws',
          name: 'Wireless ANC Earbuds (BT 5.3)',
          sku: 'ANC-TWS-BLK',
          quantity: 2000,
          factoryCostCurrency: 'CNY',
          factoryCostPerUnit: 42.0, // 42 RMB
          profitType: 'fixed',
          profitPerUnit: 2.5, // 2.5 RMB profit per unit
          unitWeightKg: 0.12,
          cbmPerUnit: 0.0003,
          packagingCostPerUnit: 1.8,
          packagingCurrency: 'CNY',
          notes: 'CE & UKCA certified, English user manual',
        },
        {
          id: 'item_charger',
          name: '30W GaN Fast Wall Charger (UK Plug)',
          sku: 'GAN-30W-UK',
          quantity: 1000,
          factoryCostCurrency: 'CNY',
          factoryCostPerUnit: 16.5, // 16.5 RMB
          profitType: 'fixed',
          profitPerUnit: 1.2, // 1.2 RMB profit per unit (~0.13 GBP)
          unitWeightKg: 0.09,
          cbmPerUnit: 0.0002,
          packagingCostPerUnit: 1.0,
          packagingCurrency: 'CNY',
          notes: 'UKCA standard plug with fuse',
        },
      ],
      shipping: {
        enabled: true,
        method: 'air_cargo_ddp',
        departurePort: 'Shenzhen Baoan Airport',
        destinationCountry: 'United Kingdom',
        destinationCity: 'London Heathrow DDP',
        calcBasis: 'per_kg',
        grossWeightKg: 330,
        volumetricWeightKg: 380,
        cbm: 1.2,
        costCurrency: 'USD',
        baseCostRate: 5.20, // $5.20 / kg
        agentProfitType: 'per_kg',
        agentProfitValue: 0.65, // Agent adds +$0.65 / kg freight profit
        transitTimeDays: '7-10 days',
        doorDeliveryIncluded: true,
        notes: 'Air Cargo DDP including UK VAT and import duty prepaid',
      },
      customs: {
        enabled: true,
        tariffPercent: 0, // already in DDP
        customsClearanceFee: 0,
        customsFeeCurrency: 'USD',
        portHandlingFee: 0,
        portFeeCurrency: 'USD',
        agentMarkupType: 'fixed',
        agentMarkupValue: 0,
        notes: 'Included in Air DDP all-in rate',
      },
      services: [
        {
          id: 'srv_lab',
          name: 'Amazon FBA / Retail Barcode Labeling',
          costCurrency: 'CNY',
          agentBaseCost: 0.15, // 0.15 RMB per piece
          clientPriceCurrency: 'GBP',
          clientPrice: 0.04, // ~0.35 RMB
          unitType: 'per_unit',
          description: 'Applying individual FNSKU barcodes and carton shipping labels',
        },
      ],
      sourcingFeeType: 'percent_product',
      sourcingFeeValue: 4.0, // 4% sourcing commission
      sourcingFeeCurrency: 'GBP',
      paymentTerms: '30% deposit, 70% before flight booking',
      leadTimeWeeks: '15 days production',
      agentCompanyName: 'DragonLink Trade & Logistics',
      agentContact: 'oliver-team@dragonlink.asia',
      notes: 'Complete DDP door delivery quotation. No surprise fees upon arrival.',
    },
  },
  {
    id: 'shipping_only_calc',
    name: 'Shipping / Freight Only Quote (Client Supplies Goods)',
    description: 'Client asking only for shipping rate from China to foreign warehouse with freight markup',
    quote: {
      id: 'quote_ship_only',
      quoteNumber: 'FRT-2026-302',
      title: 'Air DDP Freight Quote (450 kg to Germany)',
      clientName: 'Hans Weber',
      clientCompany: 'EuroTech Handel GmbH',
      clientEmail: 'h.weber@eurotech.de',
      clientCountry: 'Germany',
      dateCreated: new Date().toISOString().split('T')[0],
      validUntil: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
      incoterm: 'DDP (Delivered Duty Paid to Frankfurt)',
      mode: 'shipping_only',
      targetCurrency: 'EUR',
      items: [
        {
          id: 'item_ship_ref',
          name: 'General Cargo (Client-Supplied Goods from Yiwu)',
          quantity: 1,
          factoryCostCurrency: 'CNY',
          factoryCostPerUnit: 0,
          profitType: 'fixed',
          profitPerUnit: 0,
          unitWeightKg: 450,
          notes: '18 cartons of assorted hardware fittings',
        },
      ],
      shipping: {
        enabled: true,
        method: 'air_cargo_ddp',
        departurePort: 'Yiwu / Shanghai Pudong Airport',
        destinationCountry: 'Germany (Frankfurt Warehouse)',
        destinationCity: 'Frankfurt am Main',
        calcBasis: 'per_kg',
        grossWeightKg: 450,
        volumetricWeightKg: 480,
        cbm: 2.8,
        costCurrency: 'USD',
        baseCostRate: 5.60, // $5.60/kg base forwarder cost
        agentProfitType: 'per_kg',
        agentProfitValue: 0.85, // Agent freight margin +$0.85/kg
        transitTimeDays: '8-11 days',
        doorDeliveryIncluded: true,
        notes: 'DDP air freight with customs clearance, European import VAT & local DPD/DHL door delivery',
      },
      customs: {
        enabled: false,
        tariffPercent: 0,
        customsClearanceFee: 0,
        customsFeeCurrency: 'USD',
        portHandlingFee: 0,
        portFeeCurrency: 'USD',
        agentMarkupType: 'fixed',
        agentMarkupValue: 0,
      },
      services: [
        {
          id: 'srv_repack',
          name: 'Warehouse Consolidation & Pallet Wrapping',
          costCurrency: 'CNY',
          agentBaseCost: 180, // 180 RMB
          clientPriceCurrency: 'EUR',
          clientPrice: 55, // 55 EUR
          unitType: 'fixed',
          description: 'Inspect cartons, consolidate 3 factory shipments, shrink wrap on 2 fumigated pallets',
        },
      ],
      sourcingFeeType: 'none',
      sourcingFeeValue: 0,
      sourcingFeeCurrency: 'EUR',
      paymentTerms: '100% freight advance payment upon airway bill issuance',
      leadTimeWeeks: 'Flight departs every Tuesday & Friday',
      agentCompanyName: 'SilkRoad Forwarding & Sourcing',
      agentContact: 'freight@silkroadlogistics.cn',
      notes: 'Includes airport handling, export declaration in China, customs clearance in EU, and door delivery.',
    },
  },
  {
    id: 'service_only_calc',
    name: 'Sourcing & Quality Inspection Service Only',
    description: 'Client requires factory audit, PSI inspection, and sample verification in Guangdong',
    quote: {
      id: 'quote_srv_only',
      quoteNumber: 'SRV-2026-118',
      title: 'Factory Audit & Pre-Shipment Inspection (Guangzhou)',
      clientName: 'Claire Laurent',
      clientCompany: 'Maison Chic Imports',
      clientEmail: 'claire@maisonchic.fr',
      clientCountry: 'France',
      dateCreated: new Date().toISOString().split('T')[0],
      validUntil: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
      incoterm: 'Service Agreement',
      mode: 'service_only',
      targetCurrency: 'EUR',
      items: [
        {
          id: 'item_srv_ref',
          name: 'Sourcing & Verification Project (Cosmetics Packaging)',
          quantity: 1,
          factoryCostCurrency: 'EUR',
          factoryCostPerUnit: 0,
          profitType: 'fixed',
          profitPerUnit: 0,
          unitWeightKg: 0,
        },
      ],
      shipping: {
        enabled: false,
        method: 'air_express',
        departurePort: 'Guangzhou',
        destinationCountry: 'France',
        calcBasis: 'per_kg',
        grossWeightKg: 0,
        costCurrency: 'USD',
        baseCostRate: 0,
        agentProfitType: 'total_fixed',
        agentProfitValue: 0,
        doorDeliveryIncluded: false,
      },
      customs: {
        enabled: false,
        tariffPercent: 0,
        customsClearanceFee: 0,
        customsFeeCurrency: 'USD',
        portHandlingFee: 0,
        portFeeCurrency: 'USD',
        agentMarkupType: 'fixed',
        agentMarkupValue: 0,
      },
      services: [
        {
          id: 'srv_audit',
          name: 'Factory On-Site Audit & Background Check',
          costCurrency: 'CNY',
          agentBaseCost: 800, // 800 RMB inspector fee + travel
          clientPriceCurrency: 'EUR',
          clientPrice: 280,
          unitType: 'fixed',
          description: 'ISO verification, business license check, factory capacity, machine photos & audit report',
        },
        {
          id: 'srv_psi',
          name: 'Full Day Pre-Shipment Inspection (PSI)',
          costCurrency: 'CNY',
          agentBaseCost: 1100, // 1100 RMB
          clientPriceCurrency: 'EUR',
          clientPrice: 320,
          unitType: 'fixed',
          description: 'AQL 2.5 sample check, packaging test, barcode scan, function check with full 40-page PDF report',
        },
        {
          id: 'srv_sample',
          name: 'Sample Consolidation & Express Air Dispatch',
          costCurrency: 'CNY',
          agentBaseCost: 350, // 350 RMB DHL fee + packing
          clientPriceCurrency: 'EUR',
          clientPrice: 95,
          unitType: 'fixed',
          description: 'Collect samples from 4 suppliers, consolidate in 1 box, ship via DHL Express to France',
        },
      ],
      sourcingFeeType: 'none',
      sourcingFeeValue: 0,
      sourcingFeeCurrency: 'EUR',
      paymentTerms: '100% upfront before inspection dispatch',
      leadTimeWeeks: 'Inspection completed within 48h of booking',
      agentCompanyName: 'DragonLink Quality & Sourcing',
      agentContact: 'qc@dragonlink.asia',
      notes: 'Detailed inspection report delivered within 24 hours of inspection completion with high-res photos and video.',
    },
  },
];
